### ISSUE TITLE
The player and enemy scenes are updating the character scene?

### ISSUE THREAD

**Issue by KoopHauss** [PacktPublishing/Godot-Game-Engine-Projects#11]
I think that the enemy and player scenes are updating the character scene when changes are being made. I noticed it when I changed the collision shape for the slime. The shape changed in the character scene as well.  Then when I saved the character scene the collision shape on the player scene also changed. When I changed that shape to match the size of the "hero" sprite, the shape on the slime and in the character scene changed to match the collision shape I changed on the hero.

[Escape the Maze.zip](https://github.com/PacktPublishing/Godot-Game-Engine-Projects/files/2471276/Escape.the.Maze.zip)

**Comment by cbscribe** [comment]
This is functioning as intended. The player and enemy scenes both inherit from the character scene, and so they share the same collision shape.

In Godot, Resource objects, such as collision shapes, are shared between instances. If you don't want this to happen, you can click on the collision shape dropdown and choose "Make Unique".
