### ISSUE TITLE
Getting Errors when attempting to run the game.

### ISSUE THREAD

**Issue by KoopHauss** [PacktPublishing/Godot-Game-Engine-Projects#12]
0:00:00:0585 - Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
----------
Type:Error
Description: 
Time: 0:00:00:0585
C Error: Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
C Source: modules/gdscript/gdscript_editor.cpp:287
C Function: debug_get_stack_level_instance

0:00:01:0860 - Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
----------
Type:Error
Description: 
Time: 0:00:01:0860
C Error: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
C Source: scene/resources/scene_format_text.cpp:1225
C Function: load_interactive

0:00:01:0862 - Failed loading resource: res://maps/level1.tscn
----------
Type:Error
Description: Failed loading resource: res://maps/level1.tscn
Time: 0:00:01:0862
C Error: Method/Function Failed, returning: RES()
C Source: core/io/resource_loader.cpp:186
C Function: _load

These are the errors I get when attempting to run the game. I am completely lost. I've checked the errata and the scripts on GitHub. I'm not seeing what is wrong.  Do you any advice on what I need to do?
[Escape the Maze.zip](https://github.com/PacktPublishing/Godot-Game-Engine-Projects/files/2473875/Escape.the.Maze.zip)

**Comment by cbscribe** [comment]
The game can't load the map because the path is incorrect.

In your Globals.gd you wrote "res://maps/level1.tscn" but the file is named `Level1.tscn` and is located in a "maps/level1" folder, so this should read "res://maps/level1/Level1.tscn".
