### ISSUE TITLE
Missing code on p.49

### ISSUE THREAD

**Issue by Jalpyo** [PacktPublishing/Godot-Game-Engine-Projects#13]
extends CanvasLayer

signal start_game

This code is missing from book-------------------------------------------------------
func _input(event):
	if $StartButton.visible and event.is_action_pressed("ui_select"):
		$StartButton.emit_signal("pressed")
------------------------------------------------------------------------------------------------
I found the code by comparing the complete source code from HUD.gd to the book.

**Comment by cbscribe** [comment]
That code adds the ability to hit the spacebar and push the button instead of clicking on it. It was left out of the book for editing reasons, but doesn't affect the functioning of the project in any way.
