### ISSUE TITLE
Player ship rotation stopped working in Godot 3.1 and 3.1.1

### ISSUE THREAD

**Issue by slowb33** [PacktPublishing/Godot-Game-Engine-Projects#15]
Game is working in Godot 3.0.6
Player ship rotation stopped working in Godot 3.1 and 3.1.1
Loading it in Godot 3.1 or 3.1.1 caused that you can't maneuver the ship rotation.

Is it a change between the versions, you need to fix in your code or is it a bug in Godot 3.1 ?

**Comment by cbscribe** [comment]
It required some minor changes to the ship code. I pushed a fix you can see here: 494e6c0

Essentially, 3.1 is stricter about changing the state of collision shapes during physics processing. In `change_state()` I changed all those statements to use `call_deferred()` which makes them safe.

Note: in 3.1 I would prefer to use `set_deferred()`, but that method wasn't available in 3.0, so this keeps backward compatibility.

Thanks!
