### ISSUE TITLE
No collision of player with coins in Coin Dash!

### ISSUE THREAD

**Issue by sleipnir029** [PacktPublishing/Godot-Game-Engine-Projects#18]
Collision is not for working in Coin Dash game. Currently I'm in the **Starting a new game** portion. Player moves under the coins with the given node tree in the book. But when I change the **CoinContainer** node above the player then player moves over the coins.

**Comment by cbscribe** [comment]
Did you connect the coin's `area_entered` signal?

**Comment by sleipnir029** [comment]
Can you please elaborate? because there was nothing mentioned in the book's coin script. Only the **_on_Player_area_entered(area)** where the two groups coins and obstacles were used and in the Coin script, **_on_Coin_area_entered(area)** was used to check if the coins are spawning behind.


Another thing, I'm having problem understanding the signal system. I've read the documentation but couldn't understand. Thank you.

**Comment by cbscribe** [comment]
Sorry, I misspoke - I meant the player's. Also check in your Coin scene that you added it to the "coins" group. A symbol will appear next to the Coin's name - it looks like a box with a circle in the middle. The spelling of the group name must match how it's written on the node and in the code.

If you're having trouble understanding signals, there's a good intro in the official docs:
https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html

**Comment by sleipnir029** [comment]
Changed the group name according to the node, still not working. 
Here's the link to the project. Can you please take a look where I've made the mistake?
https://drive.google.com/drive/folders/1o48doMMIxX2CoEJ_0svUSiSn_0P2JL5W?usp=sharing

**Comment by cbscribe** [comment]
You didn't put the coin in the group, you put the coin's *CollisionShape2D* in the group. It's the root node of the coin scene that identifies the object, so it needs to be the one with the group added. When I fixed that, the player picks up the coins.

**Comment by sleipnir029** [comment]
It works now. Thanks a lot!
