### ISSUE TITLE
Grass won't tile over full background in Coin Dash using Godot 3.1.2

### ISSUE THREAD

**Issue by stephensmith9** [PacktPublishing/Godot-Game-Engine-Projects#20]
Using Godot 3.1.2 and just before I started "Part 4 - User Interface" in Chapter 2 "Coin Dash" I ran what I had so far and all works well except the grass didn't tile over the entire screen (just one 64x64 square in the upper left corner).

I figured out the solution, which was to set the Rect | Size property of the TexturedRect to 480x720 (this is in the Inspector tab under Control). This wasn't mentioned in the book, however, so posting here for anyone else who runs into this problem.

One of the best intro's to Godot I've read so far though. Thanks for the great book!

**Comment by cantonsen** [comment]
I just downloaded the code, imported it in Godot 3.1.2. I was asked to convert the project, I did, and everything worked just fine.
I agree, this book is a really good introduction to Godot.

**Comment by cbscribe** [comment]
You can also click the "Layout -> Full Rect" option for the TextureRect.

Glad you found a solution!
