### ISSUE TITLE
Coin Dash - Coin still triggering player area entered

### ISSUE THREAD

**Issue by oronbz** [PacktPublishing/Godot-Game-Engine-Projects#27]
Fixed on: https://github.com/PacktPublishing/Godot-Game-Engine-Projects/pull/26

**Comment by oronbz** [comment]
@cbscribe you might want to fix this on `errata.md` as well, I have the `epub` version and don't know what actual page is it.

**Comment by shruthis-shetty** [comment]
Hi @cbscribe , I hope you got the solution to this issue. Please do let us know the updates.

**Comment by oronbz** [comment]
> Hi @cbscribe , I hope you got the solution to this issue. Please do let us know the updates.

I've created a pull request with the fix #26

**Comment by shruthis-shetty** [comment]
Hi @oronbz , check now.

**Comment by oronbz** [comment]
> @cbscribe you might want to fix this on `errata.md` as well, I have the `epub` version and don't know what actual page is it.

Awesome, please regard to this as well 👆

**Comment by shruthis-shetty** [comment]
Hi @cbscribe, I'll update the errata.md as well but please let me know in which chapter you're facing this issue?
