### ISSUE TITLE
No collisions between player and rocks in SpaceRocks

### ISSUE THREAD

**Issue by JohnLudlow** [PacktPublishing/Godot-Game-Engine-Projects#29]
I'm following the SpaceRocks project but I'm having an issue with detecting Player / Rock collisions. This is almost certainly something I'm doing wrong, I'd just appreciate a pointer as to what that might be.

I've connected a signal to a C# (yes I'm using C#) method on `Player.on_body_entered`:

![image](https://github.com/user-attachments/assets/a1c964cb-7216-47f2-b3a1-3d8c1214eda0)

```csharp
	public void OnBodyEntered(Node body)
	{
		Debug.WriteLine("collided with something!");
		if (body.IsInGroup("rocks") && body is Rock rock)
		{
			rock.Explode();
			Lives--;
			Explode();
		}
	}
```

The problem is this signal's method is never invoked. I've put a breakpoint at the start of this method and it's just never hit when the player ship and rock meet. I also never see the debug output.

# My code for my current attempt
[JohnLudlow / GodotTraining / SpackeRocks](https://github.com/JohnLudlow/GodotTraining/tree/main/SpaceRocks)

# Things I've already checked
* The player has contact monitor enabled:
![image](https://github.com/user-attachments/assets/0d929ed4-34a4-4838-a4c9-450b1674919d)

* The player has a collision shape:
![image](https://github.com/user-attachments/assets/0703ff06-9177-4184-8b94-cb5663a4b16c)

* The rocks have a collision shape
![image](https://github.com/user-attachments/assets/67433f39-af44-42e8-ad2b-d7e29c586bf9)

* Collisions between rocks and bullets (which are Area2D's) work fine (which also suggests the collision shape is correct)

* I've downloaded the sample project and compared property-by-property and can't see what I'm missing

* I've made a much simpler project to test collisions between RigidBody2D objects: [JohnLudlow / GodotTraining / 2dColisionTester](https://github.com/JohnLudlow/GodotTraining/tree/main/2dColisionTester) and collisions do trigger the signal.

# Conclusion

So I'm pretty sure this is something obvious I'm missing but I can't see what so I'd really appreciate a pointer or two.

**Comment by nathanjwtx** [comment]
Are the collision layers setup correctly?

**Comment by JohnLudlow** [comment]
Thanks for the quick response and that's a good thing to check. If I remember correctly, the project in the book doesn't ask you to do anything specific with the collision layers. 

Also, the demo project in this repo works and just has the default collision layers for the player:

![image](https://github.com/user-attachments/assets/74bffa91-703a-4820-9a37-afbea681f045)

Here's the version from my project.

![image](https://github.com/user-attachments/assets/65a9f02d-6181-4762-a5b4-0eefce56d120)

It's the same for the rock (everything's on layer 1, mask 1)

Is there somewhere else I should be looking? Do the layers for the rock need to be tweaked in code as it's spawned or something?

**Comment by nathanjwtx** [comment]
When I pulled your project, the collision shape on the rock had no shape set. Looking at the *.tscn file in Github it shows no subresource. I'm using 4.3 so it could be shown differently in the file.

This is what it looks like in the Player.tscn: [link](https://github.com/JohnLudlow/GodotTraining/blob/32a745e1f3bd99b9f479cd10576b999c725d56a2/SpaceRocks/Player/Player.tscn#L26)

Your Rock: [link](https://github.com/JohnLudlow/GodotTraining/blob/32a745e1f3bd99b9f479cd10576b999c725d56a2/SpaceRocks/Rock/Rock.tscn#L21)

**Comment by JohnLudlow** [comment]
Hmmm, I sort of see what's happened. I might have accidentally posted this in the wrong github repo. I'm working with v4 of the engine and the corresponding book with v4, but I've mistakenly raised this issue on the pre-v4 repo.

In the v4 version of the book, it's similar to what I have posted, with a CollisionShape2D with no child resources: [v4 example rock.tscn](https://github.com/PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition/blob/main/Chapter03%20-%20Space%20Rocks/space_rocks/rock.tscn). The shape is created and assigned in the `start` function in `rock.gd` in the example, and in the Start method in Rock.cs in my code:

![image](https://github.com/user-attachments/assets/53dac634-7c9c-4114-8d38-1e7eb3cc0169)

Sorry about that - I'll re-raise this in the proper place for v4.

Also, thanks for taking the time to respond and help me out.

**Comment by JohnLudlow** [comment]
Reraised as https://github.com/PacktPublishing/Godot-4-Game-Development-Projects-Second-Edition/issues/29

Thanks for your time and help
