### ISSUE TITLE
Invalid set index 'screensize' (on base: 'Area2D (Coin.gd)') with value of type 'Vector2'.

### ISSUE THREAD

**Issue by shazzner** [PacktPublishing/Godot-Game-Engine-Projects#4]
Hi there, I'm having an issue with the first example project.

I'm at the point where I'm adding the script to the Main node, in the `spawn_coins()` function I get a compile error when `c.screensize = screensize`. 

I dragged the Coin.tscn to the exported Coin variable.

```
extends Node

export (PackedScene) var Coin
export (int) var playtime
var level
var score
var time_left
var screensize
var playing = false

# ..._ready() and new_game() go here...

func spawn_coins():
	for i in range(4 + level):
		var c = Coin.instance()
		$CoinContainer.add_child(c)
                # Errors here:
		c.screensize = screensize
		c.position = Vector2(rand_range(0, screensize.x),rand_range(0, screensize.y))
```

Any ideas on what I'm doing wrong?

**Comment by shazzner** [comment]
Looks like I figured it out, in the book it seems to be missing a var in the Coin.gd script.

What the book shows:
```
extends Area2D

func pickup():
    queue_free()
```

What it should be:
```
extends Area2D

var screensize

func pickup():
	queue_free()
```

**Comment by cbscribe** [comment]
FYI, this and other errata are listed here:
https://github.com/PacktPublishing/Godot-Game-Engine-Projects/blob/master/errata.md#chapter-2
