### ISSUE TITLE
Error: Invalid Call. Nonexistent function 'length' in base 'Vector2'

### ISSUE THREAD

**Issue by KoopHauss** [PacktPublishing/Godot-Game-Engine-Projects#5]
So I received this error when trying to run the scene after finishing the animation portion of the tutorial. I checked my spelling several times and checked the script against the provided Git-Hub script and nothing was wrong. 
Eventually I did get it to work but, maybe as a fluke, because all I did was delete that line of code and retype it a few times and eventually the game played.
Is this a normal bug of the engine, and something to be expected, which is fine? Or, is there a more efficient way of coding in the animations that the engine or game would prefer or/and expect(s)?

**Comment by cbscribe** [comment]
It's a little hard to diagnose what went wrong from just your description. In the future, when you have an error like this, share the exact code that's causing it. As it is, I can't really guess what it might have been. If you deleted and retyped it, then you must have fixed whatever error you had made.

**Comment by KoopHauss** [comment]
Okay. Thanks.

**Comment by VortexAcherontic** [comment]
I had this issue too just today as I tried to work on the FPS tutorial, here is the code:

````
func joypad_move_input():
	if Input.get_connected_joypads().size() > 0:
		var joypad_vec = Vector2(0, 0)
		if OS.get_name() == "Windows":
			joypad_vec = Vector2(Input.get_joy_axis(0, 0), -Input.get_joy_axis(0, 1))
		else:
			joypad_vec = Vector2(Input.get_joy_axis(0, 1), -Input.get_joy_axis(0, 2))
		if joypad_vec.length() < JOYPAD_DEADZONE:
			joypad_vec = Vector2(0, 0)
		else:
			joypad_vec = joypad_vec.normalized() * ((joypad_vec.lenght() - JOYPAD_DEADZONE) / (1 - JOYPAD_DEADZONE))
		input_movement_vector += joypad_vec
````

Godot Engine v3.1.1.stable
